# Generated by Django 5.2.7 on 2025-11-12 00:11

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction ID from Chapa', max_length=255, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('currency', models.CharField(default='ETB', help_text='Currency code (ETB for Ethiopian Birr)', max_length=3)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('payment_method', models.CharField(blank=True, help_text='Payment method used (e.g., mobile, card)', max_length=50, null=True)),
                ('chapa_reference', models.CharField(help_text='Unique reference for this payment in Chapa', max_length=255, unique=True)),
                ('checkout_url', models.URLField(blank=True, help_text='Chapa checkout URL for user to complete payment', max_length=500, null=True)),
                ('payment_date', models.DateTimeField(blank=True, help_text='Date and time when payment was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='listings.booking')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking'], name='payments_booking_4c4815_idx'), models.Index(fields=['transaction_id'], name='payments_transac_a1f824_idx'), models.Index(fields=['payment_status'], name='payments_payment_bbdde9_idx'), models.Index(fields=['chapa_reference'], name='payments_chapa_r_7cab2e_idx')],
            },
        ),
    ]
